<a href="https://colab.research.google.com/github/sajid-munawar/100_plus_python_challenging_programs/blob/master/100%2B_Python_challenges.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

100+ Python challenging programming exercises

Level description


Level 1	Beginner:

Means someone who has just gone through an introductory Python course. He can solve some problems with 1 or 2 Python classes or functions. Normally, the answers could directly be found in the textbooks.

Level 2 Intermediate:

Means someone who has just learned Python, but already has a relatively strong programming background from before. He should be able to solve problems which may involve 3 or 3 Python classes or functions. The answers cannot be directly be found in the textbooks.

Level 3	Advanced:

He should use Python to solve more complex problem using more rich libraries functions and data structures and algorithms. He is supposed to solve the problem using several Python standard packages and advanced techniques.



2.	Problem template

#----------------------------------------#
Question

Hints

Solution

3.	Questions

#----------------------------------------#


Question 1
Level 1

Question:
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.

In [ ]:
for i in range(2000,3200+1):
  if i%7==0 and i%5!=0:
    print(i,end=',')

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199,

In [ ]:
alist=[]
for i in range(2000,3200+1):
  if i%7==0 and i%5!=0:
    alist.append(i)
  # print(i,end=' ')
print(alist)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [ ]:
alist1=[str(y) for y in range(2000,3201) if y%7==0 if y%5!=0]
print(",".join((alist1)))
# print(alist1)

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


In [ ]:


# Hints:
# Consider use range(#begin, #end) method

# Solution:
l=[]
for i in range(2000, 3201):
    if (i%7==0) and (i%5!=0):
        l.append(str(i))

print(','.join(l))
#----------------------------------------#

2002,,2009,,2016,,2023,,2037,,2044,,2051,,2058,,2072,,2079,,2086,,2093,,2107,,2114,,2121,,2128,,2142,,2149,,2156,,2163,,2177,,2184,,2191,,2198,,2212,,2219,,2226,,2233,,2247,,2254,,2261,,2268,,2282,,2289,,2296,,2303,,2317,,2324,,2331,,2338,,2352,,2359,,2366,,2373,,2387,,2394,,2401,,2408,,2422,,2429,,2436,,2443,,2457,,2464,,2471,,2478,,2492,,2499,,2506,,2513,,2527,,2534,,2541,,2548,,2562,,2569,,2576,,2583,,2597,,2604,,2611,,2618,,2632,,2639,,2646,,2653,,2667,,2674,,2681,,2688,,2702,,2709,,2716,,2723,,2737,,2744,,2751,,2758,,2772,,2779,,2786,,2793,,2807,,2814,,2821,,2828,,2842,,2849,,2856,,2863,,2877,,2884,,2891,,2898,,2912,,2919,,2926,,2933,,2947,,2954,,2961,,2968,,2982,,2989,,2996,,3003,,3017,,3024,,3031,,3038,,3052,,3059,,3066,,3073,,3087,,3094,,3101,,3108,,3122,,3129,,3136,,3143,,3157,,3164,,3171,,3178,,3192,,3199


#----------------------------------------#
Question 2
Level 1

Question:

Write a program which can compute the factorial of a given numbers.
The results should be printed in a comma-separated sequence on a single line.
Suppose the following input is supplied to the program:

8

Then, the output should be:

40320

In [ ]:
num=int(input('please enter num'))
a=1
for i in range(1,num+1):
  a*=i
  print(a,end=',')

please enter num8
1,2,6,24,120,720,5040,40320,

In [ ]:
alist=[]
num=int(input('please enter num'))
a=1
for i in range(1,num+1):
  a*=i
  alist.append(str(a))
print(','.join(alist))

please enter num8
1,2,6,24,120,720,5040,40320


In [ ]:
(lambda x:x*x-1)(7)

48

In [ ]:
1*2*3*4*5*6*7*8

40320

In [ ]:
# Hints:
# In case of input data being supplied to the question, it should be assumed to be a console input.

# Solution:
def fact(x):
    if x == 0:
        return 1
    return x * fact(x - 1)

x=int(input())
print(fact(x))
#----------------------------------------#

8
40320


In [ ]:
def abc(x):
  if x==0:
    return 1
  # abc(x-4)
  return x*fact(x-1)

In [ ]:
# fact(968) max limit

#----------------------------------------#
Question 3
Level 1

Question:

With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.
Suppose the following input is supplied to the program:

8

Then, the output should be:

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [ ]:
def dic(x):
  dictionary={}
  for i in range(1,x+1):
    dictionary[i]=i*i
  print(dictionary)

In [ ]:
dic(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [ ]:
# Hints:
# In case of input data being supplied to the question, it should be assumed to be a console input.
# Consider use dict()

# Solution:
n=int(input())
d=dict()
for i in range(1,n+1):
    d[i]=i*i

print(d)
#----------------------------------------#

8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [ ]:
#----------------------------------------#
Question 4
Level 1

Question:

Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.
Suppose the following input is supplied to the program:

34,67,55,33,12,98

Then, the output should be:

['34', '67', '55', '33', '12', '98']
('34', '67', '55', '33', '12', '98')


In [ ]:
values=input()
alist=values.split(',')
tup=tuple(alist)
print(alist)
print(tup)

22,33,44,55
['22', '33', '44', '55']
('22', '33', '44', '55')


In [ ]:
# Hints:
# In case of input data being supplied to the question, it should be assumed to be a console input.
# tuple() method can convert list to tuple

# Solution:
values=input()
l=values.split(",")
t=tuple(l)
print(l)
print(t)
#----------------------------------------#


33,44,55
['33', '44', '55']
('33', '44', '55')


#----------------------------------------#
Question 5
Level 1

Question:

Define a class which has at least two methods:

getString: 

to get a string from console input


printString: 

to print the string in upper case.

Also please include simple test function to test the class methods.

In [20]:
class Car():
  def __init__(self):
    self=self

  def getString(self):
    self.string=input('Please enter the string ')
  def printString(self):
    print(self.string.upper())

In [21]:
car1=Car()

In [22]:
car1.getString()

Please enter the string my name is sajid


In [23]:
car1.printString()

MY NAME IS SAJID


In [24]:
# Hints:
# Use __init__ method to construct some parameters

# Solutionmy:
class InputOutString():
    def __init__(self):
        self.s = ""

    def getString(self):
        self.s =input()

    def printString(self):
        print(self.s.upper())

strObj = InputOutString()
strObj.getString()
strObj.printString()
#----------------------------------------#

my name is Sajid
MY NAME IS SAJID


#----------------------------------------#
'''Question 6
Level 2

Question:
Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24
'''

In [52]:
def formula():
  valuess=input()
  final=[]
  alist=valuess.split(',')
  for i in range(len(alist)):
    final.append(str(int(sqrt(2*50*int((alist[i]))//30))))
  print(','.join(final))
  # return alist

In [55]:
'''
Hints:
If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26)
In case of input data being supplied to the question, it should be assumed to be a console input. 

Solution:
#!/usr/bin/env python'''
import math
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print(','.join(value))
#----------------------------------------#

100,150,180
18,22,24


'''#----------------------------------------#
Question 7

Level 2

Question:

Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array.
 The element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡­Y-1.
Example

Suppose the following inputs are given to the program:
3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0],

 [0, 1, 2, 3, 4],

 [0, 2, 4, 6, 8]] 

'''

In [78]:
import numpy as np
digits=[x for x in input().split(',')]
arr=np.zeros((int(digits[0]),int(digits[1])))
# print(arr)
for row in range((arr.shape[0])):
  for column in range(arr.shape[1]):
    arr[row][column]=row*column
print(arr)

3,5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [81]:
'''Hints:
Note: In case of input data being supplied to the question, it should be assumed to be a console input in a comma-separated form.

Solution:
'''
input_str = input()
dimensions=[int(x) for x in input_str.split(',')]
rowNum=dimensions[0]
colNum=dimensions[1]
multilist = [[0 for col in range(colNum)] for row in range(rowNum)]

for row in range(rowNum):
    for col in range(colNum):
        multilist[row][col]= row*col

print(multilist)
#----------------------------------------#

3,5
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


In [79]:
input_str = input()
dimensions=[int(x) for x in input_str.split(',')]
rowNum=dimensions[0]
colNum=dimensions[1]
multilist = [[0 for col in range(colNum)] for row in range(rowNum)]

3,5


In [80]:
multilist

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [84]:
ord('p')

112