<a href="https://colab.research.google.com/github/sajid-munawar/100-python-challenging-program/blob/master/Deep_learning_first_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.4.1'

In [2]:
from tensorflow.keras.datasets import mnist

In [3]:
(train_images, train_labels),(test_images,test_labels)=mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
# to convert any data into numbers is called vactorization

In [6]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [7]:
train_images[0].ndim

2

In [8]:
train_images[0].shape

(28, 28)

In [9]:
test_images.shape

(10000, 28, 28)

In [10]:
train_labels[0]

5

In [11]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [12]:
len(test_labels)

10000

In [13]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

Listing 2.2 The network architecture

In [14]:
from tensorflow.keras import models
from tensorflow.keras import layers
network =models.Sequential()
network.add(layers.Dense(512,activation='relu',input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))

In [16]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'] )

In [18]:
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype('float32')/255

In [20]:
test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype('float32')/255

In [21]:
from tensorflow.keras.utils import to_categorical

In [22]:
train_labels=to_categorical(train_labels)

In [23]:
test_labels=to_categorical(test_labels)

In [24]:
network.fit(train_images,train_labels,epochs=5,batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 7ms/step - loss: 0.4171 - accuracy: 0.8789
Epoch 2/5
469/469 [==============================] - 4s 8ms/step - loss: 0.1094 - accuracy: 0.9685
Epoch 3/5
469/469 [==============================] - 4s 7ms/step - loss: 0.0690 - accuracy: 0.9794
Epoch 4/5
469/469 [==============================] - 3s 7ms/step - loss: 0.0460 - accuracy: 0.9854
Epoch 5/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0370 - accuracy: 0.9893


In [25]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.0693 - accuracy: 0.9793


In [31]:
print("test acc= ",test_acc)

test acc=  0.9793000221252441
